#!/usr/bin/python
import os
from cmdhelper.CmdHelper import *

if __name__ == "__main__":
    args = sys.argv
    if len(args) < 2:
        print "Error in Parameters"
        exit()

    cmdHelper = CmdHelper()

    if(args[1] == "set"):
        try:
            if(len(args) > 3 and ["uid","host","pwd"].index(args[2]) > -1):
                cmdHelper.set_config(args[2],args[3])
        except:
            print "Error in Parameters"
            exit()
    if(args[1] == "list"):
        cmdHelper.list_config()

    if(args[1] == "push"):
        cmdHelper.push()

    if(args[1] == "pull"):
        cmdHelper.pull()

    exit()




















