#!/usr/bin/python
from cmdhelper.CmdHelper import *
#import sys
#sys.path.append('/Projects/python/cmdhelper')
#from src.cmdhelper.CmdHelper import *

args = sys.argv

if len(args) < 2:
   exit()

cmdHelper = CmdHelper()
cmdHelper.mark(args[1])
