#!/usr/bin/python
import os
from cmdhelper.CmdHelper import *

args = sys.argv

if len(args) < 2:
   exit()

cmdHelper = CmdHelper()
command = cmdHelper.get(args[1])
if (command == None):
    print("Key not exist")
    exit()

if(command['type'] == 'c'):
    print("Going to run: " + str(command['value']))
    os.system(command["value"])
else:
    print(str(command['value']))